version: "2"

services:
    drupal-web:
        image: "drupal:8.8.2"
        ports:
            - "8080:80"
        restart: "always"
        volumes: 
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes  
    postgresql:
        image: "postgres"
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: user
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"
        restart: "always"
        
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: