# create your drupal and postgres config here, based off the last assignment
version: "2"

services:
    drupal-web:
        image: "custom-drupal"
        build:
            context: .
            dockerfile: Dockerfile
        image: drupal-custom
        ports:
            - "8080:80"
        restart: "always"
        volumes: 
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes  
    postgresql:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"
        volumes:
            - drupal-data:/var/lib/postgresql/data
        
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data: